import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CodeHunter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">CodeHunter!</a>
        </h1>

        <Image src = "/home.jpeg" width={160} height={240} className={styles.imgh}></Image>

        <p className={styles.description}>
          From a Coder by a <code>Coder</code>
        </p>
        
        <div className="blogs">
          <h2>Latest Blogs</h2>
          <div className="blog">
            <h3>How to learn JavaScript</h3>
            <p>A language to build logic for webpages</p>
          </div>
          <div className="blog">
            <h3>How to learn JavaScript</h3>
            <p>A language to build logic for webpages</p>
          </div>
          <div className="blog">
            <h3>How to learn JavaScript</h3>
            <p>A language to build logic for webpages</p>
          </div>
        </div>

      </main>

      {/* <footer className={styles.footer}>
      </footer> */}
    </div>
  )
}
